#This is the first version of the math quiz

print("")
print("---Welcome to the Math Quiz---")
print("")
print("To ensure your safety, we will ask some questions.")
print("")
name = input("Enter your name here: ")
age = int(input("Enter your age here: "))

if age <=(10):
    print("You are not eligible for this quiz!")
    print("Have a good day!")

if age >=(19):
    print("You are not eligible for this quiz!")
    print("Have a good day!")
    
if age in range(11,19):
          print("")
          print("You are eligible for this quiz!")
          print("")
          print("For each question, you will be given 4 choices, please choose from there!")
          print("When entering your answer, PLEASE ENTER FROM 1-4!")
          print("Best of luck!")
          print("")
          print("---Level 1---")
          print("")
          print("---Question 1---")
          print("")
          print("1. 36")
          print("2. 37")
          print("3. 27")
          print("4. 41")
          print("")
          question = input("18+19= ")
          if question =="2":
              print("")
              print("Correct!")
          else:
              print("")
              print("Incorrect!")
              print("The correct answer is 2. 37!")
          print("")
          print("---Question 2---")
          print("")
          print("1. 57")
          print("2. 37")
          print("3. 63")
          print("4. 27")
          print("")
          question = input("19*3= ")
          if question =="1":
              print("")
              print("Correct!")
          else:
              print("")
              print("Incorrect!")
              print("The correct answer is 1. 57!")
          print("")
          print("---Question 3---")
          print("")
          print("1. 20")
          print("2. 5")
          print("3. 45")
          print("4. 10")
          print("")
          question = input("50/5= ")
          if question =="4":
              print("")
              print("Correct!")
          else:
              print("")
              print("Incorrect!")
              print("The correct answer is 4. 10!")
          print("")
          print("---Question 4---")
          print("")
          print("1. 16")
          print("2. 41")
          print("3. 17")
          print("4. 10")
          print("")
          question = input("29-12= ")
          if question =="3":
              print("")
              print("Correct!")
          else:
              print("")
              print("Incorrect!")
              print("The correct answer is 3. 17!")
          print("")
          print("---Question 5---")
          print("")
          print("1. 55")
          print("2. 64")
          print("3. 46")
          print("4. 49")
          print("")
          question = input("8²= ")
          if question =="2":
              print("")
              print("Correct!")
          else:
              print("")
              print("Incorrect!")
              print("The correct answer is 2. 64!")
          print("")
          print("---Question 6---")
          print("")
          print("1. 9")
          print("2. 13")
          print("3. 7")
          print("4. 27")
          print("")
          question = input("√49=  ")
          if question =="3":
              print("")
              print("Correct!")
          else:
              print("")
              print("Incorrect!")
              print("The correct answer is 3. 7!")
          print("")
          print("---Question 7---")
          print("")
          print("1. 114")
          print("2. 112")
          print("3. 75")
          print("4. 118")
          print("")
          question = input("51*2+(4+8)= ")
          if question =="1":
              print("")
              print("Correct!")
              print("")
              print("-------------------------------------------")
              print("Congratulations",name,"! You completed the quiz!")
              print("-------------------------------------------")
          else:
              print("")
              print("Incorrect")
              print("The correct answer is 1. 114")
              print("")
              print("-------------------------------------------")
              print("Congratulations",name,"! You completed the quiz!")
              print("-------------------------------------------")
                             
